project:
  type: website
  output-dir: docs

website:
  title: "Machine learning from scratch"
  sidebar:
    style: docked
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "Set-up"
        contents:
          - setup.qmd
          - basic-jupyter.qmd
          - task_setup.qmd
      - section: "What is machine learning?"
        contents:
          - ml-overview.qmd
          - Regression_from_scratch.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



